from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import matplotlib.pyplot as plt
from PyQt5 import QtCore, QtGui, QtWidgets
import os

BASE_DIR = os.path.dirname(os.path.realpath(__file__))

# class Ui_MainWindow(object):
#     def setupUi(self, MainWindow):
#         MainWindow.setObjectName("MainWindow")
#         MainWindow.resize(929, 827)
#         self.centralwidget = QtWidgets.QWidget(MainWindow)
#         self.centralwidget.setEnabled(True)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
#         self.centralwidget.setSizePolicy(sizePolicy)
#         self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
#         self.centralwidget.setObjectName("centralwidget")
#         self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
#         self.gridLayout.setObjectName("gridLayout")
#         self.splitter_4 = QtWidgets.QSplitter(self.centralwidget)
#         self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
#         self.splitter_4.setObjectName("splitter_4")
#         self.layoutWidget = QtWidgets.QWidget(self.splitter_4)
#         self.layoutWidget.setObjectName("layoutWidget")
#         self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
#         self.verticalLayout.setContentsMargins(0, 0, 0, 0)
#         self.verticalLayout.setObjectName("verticalLayout")
#         self.horizontalLayout = QtWidgets.QHBoxLayout()
#         self.horizontalLayout.setObjectName("horizontalLayout")
#         self.label_project_name = QtWidgets.QLabel(self.layoutWidget)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.label_project_name.sizePolicy().hasHeightForWidth())
#         self.label_project_name.setSizePolicy(sizePolicy)
#         font = QtGui.QFont()
#         font.setFamily("微軟正黑體")
#         font.setPointSize(16)
#         font.setBold(True)
#         font.setWeight(75)
#         self.label_project_name.setFont(font)
#         self.label_project_name.setLayoutDirection(QtCore.Qt.LeftToRight)
#         self.label_project_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
#         self.label_project_name.setObjectName("label_project_name")
#         self.horizontalLayout.addWidget(self.label_project_name)
#         self.label_project_item_name = QtWidgets.QLabel(self.layoutWidget)
#         font = QtGui.QFont()
#         font.setFamily("微軟正黑體")
#         font.setPointSize(16)
#         font.setBold(True)
#         font.setWeight(75)
#         self.label_project_item_name.setFont(font)
#         self.label_project_item_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
#         self.label_project_item_name.setObjectName("label_project_item_name")
#         self.horizontalLayout.addWidget(self.label_project_item_name)
#         self.verticalLayout.addLayout(self.horizontalLayout)
#         self.splitter_2 = QtWidgets.QSplitter(self.layoutWidget)
#         self.splitter_2.setOrientation(QtCore.Qt.Vertical)
#         self.splitter_2.setObjectName("splitter_2")
#         self.label_item_image = QtWidgets.QLabel(self.splitter_2)
#         self.label_item_image.setEnabled(True)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.label_item_image.sizePolicy().hasHeightForWidth())
#         self.label_item_image.setSizePolicy(sizePolicy)
#         self.label_item_image.setMaximumSize(QtCore.QSize(800, 600))
#         self.label_item_image.setText("")
#         self.label_item_image.setPixmap(QtGui.QPixmap(":/newPrefix/messageImage_1600330717366.jpg"))
#         self.label_item_image.setScaledContents(True)
#         self.label_item_image.setAlignment(QtCore.Qt.AlignCenter)
#         self.label_item_image.setObjectName("label_item_image")
#         self.splitter = QtWidgets.QSplitter(self.splitter_2)
#         self.splitter.setOrientation(QtCore.Qt.Horizontal)
#         self.splitter.setObjectName("splitter")
#         self.tableWidget_project_item = QtWidgets.QTableWidget(self.splitter)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.tableWidget_project_item.sizePolicy().hasHeightForWidth())
#         self.tableWidget_project_item.setSizePolicy(sizePolicy)
#         self.tableWidget_project_item.setObjectName("tableWidget_project_item")
#         self.tableWidget_project_item.setColumnCount(0)
#         self.tableWidget_project_item.setRowCount(0)
#         self.label_gonogo = QtWidgets.QLabel(self.splitter)
#         self.label_gonogo.setEnabled(True)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.label_gonogo.sizePolicy().hasHeightForWidth())
#         self.label_gonogo.setSizePolicy(sizePolicy)
#         self.label_gonogo.setObjectName("label_gonogo")
#         self.verticalLayout.addWidget(self.splitter_2)
#         self.layoutWidget1 = QtWidgets.QWidget(self.splitter_4)
#         self.layoutWidget1.setObjectName("layoutWidget1")
#         self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
#         self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
#         self.verticalLayout_2.setObjectName("verticalLayout_2")
#         self.label_project_item_name_2 = QtWidgets.QLabel(self.layoutWidget1)
#         font = QtGui.QFont()
#         font.setFamily("微軟正黑體")
#         font.setPointSize(16)
#         font.setBold(True)
#         font.setWeight(75)
#         self.label_project_item_name_2.setFont(font)
#         self.label_project_item_name_2.setAlignment(QtCore.Qt.AlignCenter)
#         self.label_project_item_name_2.setObjectName("label_project_item_name_2")
#         self.verticalLayout_2.addWidget(self.label_project_item_name_2)
#         self.splitter_3 = QtWidgets.QSplitter(self.layoutWidget1)
#         self.splitter_3.setOrientation(QtCore.Qt.Vertical)
#         self.splitter_3.setObjectName("splitter_3")
#         self.tableWidget_measure = QtWidgets.QTableWidget(self.splitter_3)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.tableWidget_measure.sizePolicy().hasHeightForWidth())
#         self.tableWidget_measure.setSizePolicy(sizePolicy)
#         self.tableWidget_measure.setMaximumSize(QtCore.QSize(3000, 600))
#         self.tableWidget_measure.setObjectName("tableWidget_measure")
#         self.tableWidget_measure.setColumnCount(0)
#         self.tableWidget_measure.setRowCount(0)
#
#
#         # -------------------------------------------------------
#         self.figure = plt.figure()
#
#         self.canvas = FigureCanvas(self.figure)
#         # self.canvas = QtWidgets.QLabel(self.splitter)
#         self.splitter_3.addWidget(self.canvas)  # 更改處
#         # -------------------------------------------------------
#
#         # self.label_5 = QtWidgets.QLabel(self.splitter_3)
#
#
#         sizePolicy.setHeightForWidth(self.canvas.sizePolicy().hasHeightForWidth())
#
#         self.canvas.setSizePolicy(sizePolicy)
#
#         # self.label_5.setText("")
#         # self.label_5.setPixmap(QtGui.QPixmap(":/newPrefix/螢幕擷取畫面 2020-09-17 163652.png"))
#         # self.label_5.setScaledContents(True)
#         # self.label_5.setObjectName("label_5")
#
#
#
#         self.verticalLayout_2.addWidget(self.splitter_3)
#         self.gridLayout.addWidget(self.splitter_4, 0, 0, 1, 1)
#         MainWindow.setCentralWidget(self.centralwidget)
#         self.menubar = QtWidgets.QMenuBar(MainWindow)
#         self.menubar.setGeometry(QtCore.QRect(0, 0, 929, 21))
#         self.menubar.setObjectName("menubar")
#         MainWindow.setMenuBar(self.menubar)
#         self.statusbar = QtWidgets.QStatusBar(MainWindow)
#         self.statusbar.setObjectName("statusbar")
#         MainWindow.setStatusBar(self.statusbar)
#
#         self.retranslateUi(MainWindow)
#         QtCore.QMetaObject.connectSlotsByName(MainWindow)
#
#     def retranslateUi(self, MainWindow):
#         _translate = QtCore.QCoreApplication.translate
#         MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
#         self.label_project_name.setText(_translate("MainWindow", "量測專案："))
#         self.label_project_item_name.setText(_translate("MainWindow", "量測項目："))
#         self.label_gonogo.setText(_translate("MainWindow", "GONOGO"))
#         self.label_project_item_name_2.setText(_translate("MainWindow", "量測人員："))
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(929, 827)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_4 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_project_name = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_project_name.sizePolicy().hasHeightForWidth())
        self.label_project_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_project_name.setFont(font)
        self.label_project_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_project_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_project_name.setObjectName("label_project_name")
        self.horizontalLayout.addWidget(self.label_project_name)
        self.label_project_item_name = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_project_item_name.setFont(font)
        self.label_project_item_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_project_item_name.setObjectName("label_project_item_name")
        self.horizontalLayout.addWidget(self.label_project_item_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter_2 = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label_item_image = QtWidgets.QLabel(self.splitter_2)
        self.label_item_image.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_item_image.sizePolicy().hasHeightForWidth())
        self.label_item_image.setSizePolicy(sizePolicy)
        self.label_item_image.setMaximumSize(QtCore.QSize(800, 600))
        self.label_item_image.setText("")
        self.label_item_image.setPixmap(QtGui.QPixmap(":/newPrefix/messageImage_1600330717366.jpg"))
        self.label_item_image.setScaledContents(True)
        self.label_item_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_item_image.setObjectName("label_item_image")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tableWidget_project_item = QtWidgets.QTableWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_project_item.sizePolicy().hasHeightForWidth())
        self.tableWidget_project_item.setSizePolicy(sizePolicy)
        self.tableWidget_project_item.setObjectName("tableWidget_project_item")
        self.tableWidget_project_item.setColumnCount(0)
        self.tableWidget_project_item.setRowCount(0)
        self.label_gonogo = QtWidgets.QLabel(self.splitter)
        self.label_gonogo.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_gonogo.sizePolicy().hasHeightForWidth())
        self.label_gonogo.setSizePolicy(sizePolicy)
        self.label_gonogo.setObjectName("label_gonogo")
        self.verticalLayout.addWidget(self.splitter_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_project_item_name_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_project_item_name_2.setFont(font)
        self.label_project_item_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_project_item_name_2.setObjectName("label_project_item_name_2")
        self.verticalLayout_2.addWidget(self.label_project_item_name_2)
        self.splitter_3 = QtWidgets.QSplitter(self.layoutWidget1)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.tableWidget_measure = QtWidgets.QTableWidget(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_measure.sizePolicy().hasHeightForWidth())
        self.tableWidget_measure.setSizePolicy(sizePolicy)
        self.tableWidget_measure.setMaximumSize(QtCore.QSize(3000, 600))
        self.tableWidget_measure.setObjectName("tableWidget_measure")
        self.tableWidget_measure.setColumnCount(0)
        self.tableWidget_measure.setRowCount(0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_measure.sizePolicy().hasHeightForWidth())
        # -------------------------------------------------------
        self.figure = plt.figure()
        # self.label_5 = QtWidgets.QLabel(self.splitter_3)
        self.canvas = FigureCanvas(self.figure)
        self.splitter_3.addWidget(self.canvas)


        sizePolicy.setHeightForWidth(self.canvas.sizePolicy().hasHeightForWidth())
        self.canvas.setSizePolicy(sizePolicy)

        self.canvas.setSizePolicy(sizePolicy)
        # self.label_5.setText("")
        # self.label_5.setPixmap(QtGui.QPixmap(":/newPrefix/螢幕擷取畫面 2020-09-17 163652.png"))
        # self.label_5.setScaledContents(True)
        # self.label_5.setObjectName("label_5")

        self.verticalLayout_2.addWidget(self.splitter_3)
        self.gridLayout.addWidget(self.splitter_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 929, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_project_name.setText(_translate("MainWindow", "量測專案："))
        self.label_project_item_name.setText(_translate("MainWindow", "量測項目："))
        self.label_gonogo.setText(_translate("MainWindow", "GONOGO"))
        self.label_project_item_name_2.setText(_translate("MainWindow", "量測人員："))